"""add EventRow + nullable event_id FKs

Revision ID: 2ae040cca08b
Revises: bac115dd4042
Create Date: 2026-05-03 22:26:09.425523

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ae040cca08b"
down_revision: str | Sequence[str] | None = "bac115dd4042"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("catalog_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("catalog_order", sa.Integer(), nullable=False),
        sa.Column("activation_seq", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("catalog_key", name="uq_event_catalog_key"),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_activation_seq"), ["activation_seq"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_event_active"), ["active"], unique=False)
        batch_op.create_index(batch_op.f("ix_event_catalog_key"), ["catalog_key"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_event_catalog_order"), ["catalog_order"], unique=False
        )

    with op.batch_alter_table("conflict", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_conflict_event_id"), ["event_id"], unique=False)
        batch_op.create_foreign_key("fk_conflict_event_id_event", "event", ["event_id"], ["id"])

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_document_event_id"), ["event_id"], unique=False)
        batch_op.create_foreign_key("fk_document_event_id_event", "event", ["event_id"], ["id"])

    with op.batch_alter_table("extraction_step", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Uuid(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_extraction_step_event_id"), ["event_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_extraction_step_event_id_event", "event", ["event_id"], ["id"]
        )

    with op.batch_alter_table("field_write", schema=None) as batch_op:
        batch_op.add_column(sa.Column("event_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_field_write_event_id"), ["event_id"], unique=False)
        batch_op.create_foreign_key("fk_field_write_event_id_event", "event", ["event_id"], ["id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("field_write", schema=None) as batch_op:
        batch_op.drop_constraint("fk_field_write_event_id_event", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_field_write_event_id"))
        batch_op.drop_column("event_id")

    with op.batch_alter_table("extraction_step", schema=None) as batch_op:
        batch_op.drop_constraint("fk_extraction_step_event_id_event", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_extraction_step_event_id"))
        batch_op.drop_column("event_id")

    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_constraint("fk_document_event_id_event", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_document_event_id"))
        batch_op.drop_column("event_id")

    with op.batch_alter_table("conflict", schema=None) as batch_op:
        batch_op.drop_constraint("fk_conflict_event_id_event", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_conflict_event_id"))
        batch_op.drop_column("event_id")

    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_catalog_order"))
        batch_op.drop_index(batch_op.f("ix_event_catalog_key"))
        batch_op.drop_index(batch_op.f("ix_event_active"))
        batch_op.drop_index(batch_op.f("ix_event_activation_seq"))

    op.drop_table("event")
    # ### end Alembic commands ###
