"""initial baseline

Revision ID: 9e3efe52ae84
Revises:
Create Date: 2026-05-03 16:27:10.878393

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e3efe52ae84"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("blob_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_document_source_class"), ["source_class"], unique=False
        )

    op.create_table(
        "entity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "key", name="uq_entity_type_key"),
    )
    with op.batch_alter_table("entity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_entity_key"), ["key"], unique=False)
        batch_op.create_index(batch_op.f("ix_entity_type"), ["type"], unique=False)

    op.create_table(
        "extraction_step",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("input_excerpt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("output_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rule_version",
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=False),
        sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("version"),
    )
    op.create_table(
        "schema_type",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("definition_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("registered_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("name", name="uq_schema_type_name"),
    )
    op.create_table(
        "field_write",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("written_by_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("written_at", sa.DateTime(), nullable=False),
        sa.Column("source_document_id", sa.Uuid(), nullable=True),
        sa.Column("rule_version_at_write", sa.Integer(), nullable=False),
        sa.Column("extraction_step_id", sa.Uuid(), nullable=True),
        sa.Column("superseded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["extraction_step_id"],
            ["extraction_step.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["written_by_agent_id"],
            ["agent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("field_write", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_field_write_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_field_write_field_name"), ["field_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_field_write_source_document_id"), ["source_document_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_field_write_superseded"), ["superseded"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_field_write_written_at"), ["written_at"], unique=False
        )

    op.create_table(
        "rule_record",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_version", sa.Integer(), nullable=False),
        sa.Column("rule_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("payload_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["rule_version"],
            ["rule_version.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rule_record", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rule_record_rule_type"), ["rule_type"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_rule_record_rule_version"), ["rule_version"], unique=False
        )

    op.create_table(
        "conflict",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("field_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolution_winner_write_id", sa.Uuid(), nullable=True),
        sa.Column("resolver_used", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolution_winner_write_id"],
            ["field_write.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conflict", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conflict_entity_id"), ["entity_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conflict", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conflict_entity_id"))

    op.drop_table("conflict")
    with op.batch_alter_table("rule_record", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rule_record_rule_version"))
        batch_op.drop_index(batch_op.f("ix_rule_record_rule_type"))

    op.drop_table("rule_record")
    with op.batch_alter_table("field_write", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_field_write_written_at"))
        batch_op.drop_index(batch_op.f("ix_field_write_superseded"))
        batch_op.drop_index(batch_op.f("ix_field_write_source_document_id"))
        batch_op.drop_index(batch_op.f("ix_field_write_field_name"))
        batch_op.drop_index(batch_op.f("ix_field_write_entity_id"))

    op.drop_table("field_write")
    op.drop_table("schema_type")
    op.drop_table("rule_version")
    op.drop_table("extraction_step")
    with op.batch_alter_table("entity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_entity_type"))
        batch_op.drop_index(batch_op.f("ix_entity_key"))

    op.drop_table("entity")
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_source_class"))
        batch_op.drop_index(batch_op.f("ix_document_content_hash"))

    op.drop_table("document")
    op.drop_table("agent")
    # ### end Alembic commands ###
