"""add_skill_action_execution_dedupe

Revision ID: bac115dd4042
Revises: 9e3efe52ae84
Create Date: 2026-05-03 18:48:58.621223

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bac115dd4042"
down_revision: str | Sequence[str] | None = "9e3efe52ae84"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill_action_execution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scope_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("action_fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("executed_at", sa.DateTime(), nullable=False),
        sa.Column("executed_by_agent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["executed_by_agent_id"],
            ["agent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scope_key", "action_fingerprint", name="uq_skill_action_scope_fingerprint"
        ),
    )
    with op.batch_alter_table("skill_action_execution", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_skill_action_execution_action_fingerprint"),
            ["action_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_skill_action_execution_scope_key"), ["scope_key"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skill_action_execution", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_action_execution_scope_key"))
        batch_op.drop_index(batch_op.f("ix_skill_action_execution_action_fingerprint"))

    op.drop_table("skill_action_execution")
    # ### end Alembic commands ###
